"""Analysis report generation.

Produces structured JSON reports combining binary metadata, function
analysis results, and optional markdown rendering.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional


def _format_list(items: List[str], indent: str = "  ") -> str:
    return "\n".join(f"{indent}- {item}" for item in items)


def _md_metadata(vw: Any) -> str:
    arch = vw.getMeta("Architecture", "unknown")
    plat = vw.getMeta("Platform", "unknown")
    fmt = vw.getMeta("Format", "unknown")
    ep_count = len(list(getattr(vw, "getEntryPoints", lambda: [])()))
    func_count = len(list(getattr(vw, "getFunctions", lambda: [])()))
    lines = [
        "# Binary Analysis Report",
        "",
        f"- **Architecture:** {arch}",
        f"- **Platform:** {plat}",
        f"- **Format:** {fmt}",
        f"- **Entry points:** {ep_count}",
        f"- **Functions:** {func_count}",
    ]
    return "\n".join(lines)


def _md_functions(results: List[Dict[str, Any]]) -> str:
    if not results:
        return "\n## Functions\n\n*No analysis results.*"
    lines = ["\n## Functions\n"]
    for r in results:
        fva = r.get("fva", "?")
        name = r.get("name", "?")
        analysis = r.get("analysis", {})
        summary = analysis.get("summary", "No summary.")
        lines.append(f"### {name} (`{fva}`)")
        lines.append(f"**Summary:** {summary}")
        lines.append("")
    return "\n".join(lines)


def generate_report(
    vw: Any,
    results: Optional[List[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    """Generate a structured analysis report.

    Args:
        vw: The vivisect workspace.
        results: Optional list of analysis result dicts (each with 'fva', 'name', 'analysis' keys).

    Returns:
        A dict with 'metadata', 'functions', and 'markdown' keys.
    """
    results = results or []
    functions = []
    for result in results:
        raw = result.get("fva")
        fva_hex = f"0x{raw:08x}" if isinstance(raw, int) else str(raw)
        functions.append({
            "fva": fva_hex,
            "name": result.get("name", "?"),
            "analysis": result.get("analysis", {}),
        })
    metadata = {
        "architecture": vw.getMeta("Architecture", "unknown"),
        "platform": vw.getMeta("Platform", "unknown"),
        "format": vw.getMeta("Format", "unknown"),
        "function_count": len(list(getattr(vw, "getFunctions", lambda: [])())),
    }

    markdown_lines = [_md_metadata(vw)]
    if results:
        markdown_lines.append(_md_functions(functions))
    markdown_lines.append("\n---\n*Generated by Viv-AI.*")

    return {
        "metadata": metadata,
        "functions": functions,
        "markdown": "\n".join(markdown_lines),
    }
